config/routes.rb
ProjetRor::Application.routes.draw do
  resources :users
  resources :chapters
  resources :characters
  resources :scenes, only: [:create, :destroy]
  resources :anecdotes, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',        to: 'users#new',            via: 'get'
  match '/signin',        to: 'sessions#new',         via: 'get'
  match '/signout',       to: 'sessions#destroy',     via: 'delete'
  match '/help',          to: 'static_pages#help',    via: 'get'
  match '/about',         to: 'static_pages#about',   via: 'get'
  match '/contact',       to: 'static_pages#contact', via: 'get'
  match '/newCharacter',  to: 'characters#new',       via: 'get'
  match '/newAnecdote',   to: 'anecdotes#new',        via: 'get'
  match '/newScene',      to: 'scenes#new',           via: 'get'
  match '/newChapter',    to: 'chapters#new',         via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @anecdote = current_user.anecdotes.build if signed_in?
    @scene = current_user.scenes.build if signed_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  Write Your Book is a project made by Marc Destefanis, to help book writers
  during their writing process.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Marc Destefanis with this email : marc.destefanis.etu@gmail.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  With Write Your Book, you can create and navigate the following records: 
    Chapter,
    Anecdote,
    Scene.
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="center hero-unit">
    <h1>My Book</h1>
    <ul class="myButtons">
      <li>   
        <%= link_to "New Chapter", newChapter_path, class: "btn btn-large btn-primary" %>
        <%= link_to "All Chapter", chapters_path, class: "btn btn-large btn-default" %>   
      </li>
      <li>
        <%= link_to "New Character", newCharacter_path, class: "btn btn-large btn-primary" %>
        <%= link_to "All Characters", characters_path, class: "btn btn-large btn-default" %>
      </li> 
        <%= link_to "New Anecdote", newAnecdote_path, class: "btn btn-large btn-primary" %>
        <%= link_to "All Anecdotes", current_user, class: "btn btn-large btn-default" %>   
      <li>   
        <%= link_to "New Scene", newScene_path, class: "btn btn-large btn-primary" %>
        <%= link_to "All Scenes", current_user, class: "btn btn-large btn-default" %>   
      </li>
    </ul>
  </div>
<% else %>
<div class="center hero-unit">
  <h1>Write Your Book</h1>
  <h2>
    Simple and Powerful
  </h2>
    <ul class="myButtons">
      <li>
        <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
      </li>    
      <li>    
        <%= link_to "Sign in", signin_path, class: "btn btn-large btn-default" %>
      </li>
    </ul>

</div>
<% end %>